export const carData = {
	Acura: ['RDX', 'TSX'],
	Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q5', 'Q7', 'Q8', 'SQ7'],
	BMW: ['2 серия Active Tourer', '2 серия Grand Tourer', '3 серия', '5 серия', '7 серия', 'Х1', 'Х2', 'Х3', 'X4', 'X5', 'X6', 'X6M', 'X7', 'XM'],
	Chery: ['Tiggo'],
	Chevrolet: ['Bolt EUV', 'Camaro', 'Captiva', 'Cruze', 'Equinox', 'Express', 'TrailBlazer', 'Volt'],
	Citroen: ['Berlingo', 'C1', 'C3', 'C4', 'C4 Aircross', 'C4 Cactus', 'C4 Grand Picasso', 'C5', 'Grand C4 Spacetou', 'Xsara', 'Xsara Picasso'],
	Dodge: ['Challenger'],
	Fiat: ['500X', '500е', 'Grande Punto', 'Scudo'],
	Ford: ['C-MAX', 'Escape', 'Explorer', 'Focus', 'Fusion', 'Fusion USA', 'Kuga', 'Mondeo', 'Mustang', 'Tourneo Connect'],
	Geely: ['Atlas', 'Coolray', 'emgrand', 'Emgrand X7', 'SC7', 'Tugella'],
	GMC: ['Terrain'],
	Haval: ['Dargo'],
	Honda: ['Accord', 'Civic', 'CR-V', 'Crosstour', 'Fit', 'Pilot', 'Stream'],
	Hyundai: ['Accent', 'Avante', 'Creta', 'Elantra', 'i20', 'Ioniq 5', 'ix35', 'Santa Fe', 'Solaris', 'Tucson'],
	Infiniti: ['JX', 'QX30', 'QX60', 'QX70'],
	Jaguar: ['XJ'],
	Jeep: ['Compass', 'Grand Cherokee', 'Wrangler', 'Renegade', 'Cherokee', 'Commander', 'Liberty', 'Patriot'],
	Kia: ["Ceed", 'Forte', 'Optima', 'Rio', 'Soul', 'Sportage'],
	Lada: ['Largus', '2109', '2114', '2121 Нива', 'Granta', 'Kalina', 'Largus', 'Priora', 'Vesta', 'XRAY'],
	LandRover: ['Discovery', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar', 'Discovery Sport', 'Defender',],
	Lexus: ['RX', 'NX', 'UX', 'IS', 'CT', 'GS', 'LS', 'LX', 'ES', 'GX', 'LC'],
	Lifan: ['X70', 'Х60', 'Smily', 'MyWay', 'Breez', 'Cebrium', 'Murman', 'Solano', 'X50'],
	Lincoln: ['MKZ', 'MKC', 'Town Car', 'Aviator', 'Continental', 'Mark VII', 'MKX', 'Navigator'],
	Mazda: ['2', '3', '6', 'CX-3', 'Tribute', 'CX-5', 'CX-7', 'CX-9', 'MPV'],
	MercedesBenz: ['C-Класс', 'CLS', 'E-Класс', 'G-Класс', 'G-Класс AMG', 'GL-класс', 'GLC', 'GLE', 'GLE AMG', 'M-Класс', 'R-Класс', 'S-Класс', 'SLK', 'Viano', 'Vito'],
	MINI: ['Countryman', 'Hatch', 'Cooper', 'Clubman', 'Cabrio', 'Coupe'],
	Mitsubishi: ['Outlander', 'Pajero', 'Pajero Sport', 'Carisma', 'Colt', 'Lancer', 'Eclipse Cross', 'ASX', 'Galant', 'Eclipse', 'Grandis'],
	Nissan: ['Qashqai', 'Micra', 'X-Trail', 'Juke', 'Almera', 'Pathfinder', 'Terrano', 'Leaf', 'Murano', 'Qashqai+2', 'Rogue'],
	Opel: ['Astra', 'Insignia', 'Zafira', 'Corsa', 'Karl', 'Vectra', 'Crossland', 'Combo', 'Meriva', 'Grandland', 'Ampera'],
	Peugeot: ['Expert', '308', '5008', '508', '3008', '307', '406', '806', '206', '207', '2008', '208'],
	Porsche: ['Cayenne', 'Panamera', 'Macan', '924', '911', '944', 'Boxster', 'Taycan'],
	Renault: ['Megane', 'Clio', 'Duster', 'Espace', 'Kaptur', 'Laguna', 'Logan', 'Logan Stepway', 'Modus', 'Sandero', 'Scenic'],
	Saab: ['9-5', '9-3', '900', '9000'],
	SEAT: ['Leon', 'Ateca', 'Mii', 'Arona', 'Alhambra', 'Ibiza', 'Altea', 'Arosa', 'Cordoba', 'Toledo'],
	Skoda: ['Octavia', 'Rapid', 'Superb', 'Kodiaq', 'Fabia', 'Karoq', 'Roomster', 'Yeti', 'Citigo', 'Favorit', 'Felicia'],
	Subaru: ['Forester', 'Legacy', 'Outback', 'Impreza', 'Tribeca', 'XV', 'Baja', 'BRZ', 'Justy', 'Libero', 'WRX STi'],
	Suzuki: ['Grand Vitara', 'Baleno', 'SX4', 'Swift', 'Jimny', 'Liana', 'Vitara', 'Aerio', 'Alto', 'Esteem', 'Forenza'],
	Tesla: ['Model 3', 'Model S', 'Model y', 'Model X'],
	Toyota: ['RAV4', 'Camry', 'Corolla', 'Auris', 'Yaris', 'Land Cruiser', 'Avensis', 'Highlander', 'Land Cruiser Prado', 'Prius', 'C-HR'],
	Volkswagen: ['Caddy', 'Caddy MAXI', 'e-Golf', 'Golf', 'Golf Plus', 'Jetta', 'Passat', 'Passat (USA)', 'Polo Sedan', 'Sharan', 'Tiguan', 'Tiguan Allspace', 'Touareg', 'Touran'],
	Volvo: ['XC90', 'XC60', 'S60', 'S80', 'V90', 'XC40', 'V60', 'S90', 'V40', 'V70', 'S40'],
	ВАЗ: ['Granta', 'Niva Travel', 'Vesta Cross']
};
